.build-steps: &build-steps
  stage: build
  script:
  - build/build.sh
  - make install
  - make test_installed
  - make uninstall
  - make clean
  - make PHPCPP_ROOT=/tmp/deps/dist/lib THREAD_SAFE=1
  - make test
  - make clean
  - make PHPCPP_ROOT=/tmp/deps/dist/lib NATIVE_FILE=1
  - make test
  - make NATIVE_FILE=1 clean
  - make PHPCPP_ROOT=/tmp/deps/dist/lib BOOST_REGEX=1
  - make test
  - make clean
  - make PHPCPP_ROOT=/tmp/deps/dist/lib THREAD_SAFE=1 NATIVE_FILE=1 DEBUG=1 BOOST_REGEX=1 STANDALONE=1
  - make test
  - make NATIVE_FILE=1 clean

build-php72:
  image: php:7.2
  <<: *build-steps

build-php73:
  image: php:7.3
  <<: *build-steps

pages:
  image: php:5.6
  script:
  - doc/build.sh
  - mkdir public
  - mv doc/dist public/api
  artifacts:
    paths:
    - public
  only:
  - master
