name: Build

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version:
        - 7.2
        - 7.3
        - 7.4

    container: php:${{ matrix.php-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build
      run: build/ci.sh

    - name: Save
      uses: actions/upload-artifact@v2
      with:
        name: release-${{ matrix.php-version }}
        path: dist/*.tar.xz

  release:
    needs:
    - build

    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Download
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Release edge
      if: startsWith(github.ref, 'refs/tags/') == false
      run: .github/workflows/release.sh edge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release stable
      if: startsWith(github.ref, 'refs/tags/')
      run: .github/workflows/release.sh "$(basename -- "$GITHUB_REF")"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
